name: 'Sanguinius Dashboard'
description: 'Display test results summary in a GitHub Actions workflow'
author: 'Erik Emmerfors'
inputs:
  paths:
    description: Path(s) to test output file(s) to analyze
    required: true
  output:
    description: File to write with rendered output
  show:
    description: Types of tests to show in the results table
runs:
  using: 'node14'
  main: 'index.js'
branding:
  icon: check-square
  color: green