name: Report example, display summaries in actions

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demos/simple-frontend
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build
        run: |
          npm ci
          npm run build
          npm run test:ci

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        run: |
          ls -la
        with:
          junit_files: "./tests/junit/results/*.xml"

      # - name: Post results
      #   run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
