name: Report example, display summaries in actions

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demos/simple-frontend
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Beginning Summary 
        run: echo "# Summary" >> $GITHUB_STEP_SUMMARY

      - name: Build
        run: |
          npm ci
          npm run build
          npm run test

      - name: Finalizing summary
        run: echo 'end' >> $GITHUB_STEP_SUMMARY

      # - name: Post results
      #   run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
