name: Report example, display summaries in actions

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

defaults:
  run:
    working-directory: demos/simple-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build
        run: |
          npm ci
          npm run build
          npm run test:ci
          ls -la tests/junit/results/

      - uses: actions/upload-artifact@v3
        with:
          name: junit-artifact
          path: ./tests/junit/results/junit.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()

        with:
          junit_files: ./tests/junit/results/junit.xml

      # - name: Post results
      #   run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
