name: Report example, display summaries in actions

on:

  workflow_dispatch:

defaults:
  run:
    working-directory: demos/simple-frontend

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Build
        run: |
          npm ci
          npm run build
          npm run test:ci
          ls -la tests/

      - uses: actions/upload-artifact@v3
        with:
          name: junit-artifact
          path: demos/simple-frontend/tests/*.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: demos/simple-frontend/tests/*.xml

      # - name: Post results
      #   run: echo '### Hello world! :rocket:' >> $GITHUB_STEP_SUMMARY
